apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-demo-ingressroute
  namespace: default
spec:
  entryPoints:
    - web  
  routes:
    - match: Host(`app02.sananetco.com`)
      kind: Rule
      services:
        - name: nginx-demo
          port: 80
