ci_access:
  projects:
    - id: "devops-cource/devtest02"
    - id: "devops-cource/devtest03"

user_access:
  access_as:
    agent: {}
  projects:
    - id: "devops-cource/devtest02"
    - id: "devops-cource/devtest03"
